#!/usr/bin/env bash
# provision.sh — preflight the pre-install infrastructure and collect the foundation
# data for a new Odysseus + MyOwnHealth install. See docs/PROVISIONING.md.
# Read-only on the system; writes .env, <bridge>/mcp/.env, data/settings.json only.
set -uo pipefail

cd "$(dirname "$0")/.." || exit 1
REPO="$(pwd)"
say()  { printf '\n\033[1m== %s ==\033[0m\n' "$1"; }
pass() { printf '  \033[32mPASS\033[0m  %s\n' "$1"; }
miss() { printf '  \033[31mMISSING\033[0m  %s\n          fix: %s\n' "$1" "$2"; PREFLIGHT_OK=0; }
warn() { printf '  \033[33mWARN\033[0m  %s\n' "$1"; }
ask()  { local p="$1" d="${2:-}" v; if [ -n "$d" ]; then read -r -p "  $p [$d]: " v; echo "${v:-$d}"; else read -r -p "  $p: " v; echo "$v"; fi; }
asks() { local p="$1" v; read -r -s -p "  $p: " v; echo >&2; echo "$v"; }   # secret (hidden)
yes()  { local p="$1" v; read -r -p "  $p (y/N): " v; [[ "$v" =~ ^[Yy] ]]; }

PREFLIGHT_OK=1

# ───────────────────────────── A. PREFLIGHT ─────────────────────────────
say "A. Pre-install infrastructure"
[ "$(uname)" = Darwin ] && pass "macOS ($(sw_vers -productVersion 2>/dev/null))" \
  || miss "not macOS" "v1 targets macOS"

if docker info >/dev/null 2>&1; then pass "Docker Desktop running"
  else miss "Docker not running" "install/start Docker Desktop (docker.com)"; fi

if curl -fsS http://localhost:11434/api/tags >/dev/null 2>&1; then
  pass "Ollama reachable (:11434)"
  have_models="$(curl -fsS http://localhost:11434/api/tags | tr ',' '\n' | grep -oE '"name":"[^"]+"' | cut -d'"' -f4)"
  for m in gemma4 llama3.2-vision nomic-embed-text; do
    echo "$have_models" | grep -qi "$m" && pass "model: $m" || warn "model '$m' not pulled — run: ollama pull $m"
  done
else miss "Ollama not running" "install + start Ollama (ollama.com), then pull models"; fi

command -v uv >/dev/null 2>&1 && HAVE_UV=1 || HAVE_UV=0
if python3.12 --version >/dev/null 2>&1 || { python3 --version 2>&1 | grep -q '3\.12'; }; then
  pass "Python 3.12"
elif [ "$HAVE_UV" = 1 ]; then
  pass "Python 3.12 (uv will fetch it for the bridge venv)"
else
  miss "Python 3.12 not found" "install Python 3.12 (python.org) or uv (astral.sh/uv)"
fi
[ "$HAVE_UV" = 1 ] && pass "uv" || miss "uv not found" "curl -LsSf https://astral.sh/uv/install.sh | sh"
command -v git >/dev/null 2>&1 && pass "git" || miss "git not found" "install git"

free_gb="$(df -g "$REPO" 2>/dev/null | awk 'NR==2{print $4}')"
[ "${free_gb:-0}" -ge 25 ] 2>/dev/null && pass "disk: ${free_gb}GB free" || warn "disk low (${free_gb:-?}GB) — need ~25GB"
ram_gb=$(( $(sysctl -n hw.memsize 2>/dev/null || echo 0) / 1073741824 ))
[ "$ram_gb" -ge 16 ] && pass "RAM: ${ram_gb}GB" || warn "RAM ${ram_gb}GB (16GB+ recommended)"

if [ "$PREFLIGHT_OK" -ne 1 ]; then
  printf '\n\033[31mPreflight has MISSING items.\033[0m Resolve them, then re-run.\n'
  yes "Continue to collect foundation data anyway?" || exit 1
fi

# ───────────────────────────── B. FOUNDATION DATA ─────────────────────────────
if [ -f .env ] && ! yes "B. .env already exists — overwrite?"; then echo "Keeping existing .env."; exit 0; fi
say "B1. Identity & auth"
ADMIN_USER=$(ask "Admin username" "${USER:-admin}")
ADMIN_PASS=$(asks "Admin password (blank = auto-generate)")
PUID=$(ask "Host PUID" "$(id -u)"); PGID=$(ask "Host PGID" "$(id -g)")

say "B2/B3. LLM endpoints + network (defaults are usually fine)"
OLLAMA=$(ask "OLLAMA_BASE_URL" "http://host.docker.internal:11434/v1")
EMBED=$(ask "EMBEDDING_URL" "http://host.docker.internal:11434/v1/embeddings")
CHAT_MODEL=$(ask "Default chat model" "gemma4:latest")
VISION_MODEL=$(ask "Vision model" "llama3.2-vision:11b")
APP_PORT=$(ask "App port" "7000"); APP_BIND=$(ask "Bind address" "127.0.0.1")

say "B4. WHOOP wearable (optional — Enter to skip)"
WHOOP_ID=""; WHOOP_SECRET=""; WHOOP_REDIR=""
if yes "Configure WHOOP now?"; then
  WHOOP_ID=$(ask "WHOOP_CLIENT_ID"); WHOOP_SECRET=$(asks "WHOOP_CLIENT_SECRET")
  WHOOP_REDIR=$(ask "WHOOP_REDIRECT_URI" "http://localhost:${APP_PORT}/whoop/callback")
fi

say "B5. Search providers (optional — Enter to skip each)"
BRAVE=$(ask "DATA_BRAVE_API_KEY" ""); TAVILY=$(ask "TAVILY_API_KEY" ""); SERPER=$(ask "SERPER_API_KEY" "")

say "B6. Health foundation"
USER_NAME=$(ask "Your name (for the record)" "$ADMIN_USER")
TZ_=$(ask "Timezone" "$(readlink /etc/localtime 2>/dev/null | sed 's#.*/zoneinfo/##' || echo America/New_York)")
# The MyOwnHealth bridge is a SEPARATE repo (cloned per the runbook). Its WHOOP
# secret + venv live there, not in this Odysseus repo.
BRIDGE=$(ask "MyOwnHealth bridge repo path" "$HOME/myownhealth")

# ───────────────────────────── WRITE ─────────────────────────────
say "Writing config"
SXNG_SECRET="$(python3 -c 'import secrets;print(secrets.token_urlsafe(48))' 2>/dev/null || openssl rand -hex 32)"
umask 177
cat > .env <<EOF
# Generated by provision.sh — $(date). chmod 600.
APP_BIND=${APP_BIND}
APP_PORT=${APP_PORT}
AUTH_ENABLED=true
SECURE_COOKIES=true
ODYSSEUS_ADMIN_USER=${ADMIN_USER}
ODYSSEUS_ADMIN_PASSWORD=${ADMIN_PASS}
PUID=${PUID}
PGID=${PGID}
OLLAMA_BASE_URL=${OLLAMA}
EMBEDDING_URL=${EMBED}
SEARXNG_SECRET=${SXNG_SECRET}
DATA_BRAVE_API_KEY=${BRAVE}
TAVILY_API_KEY=${TAVILY}
SERPER_API_KEY=${SERPER}
SANDBOX_FALLBACK_LOCAL=false
EOF
chmod 600 .env; pass ".env (chmod 600)"

if [ -n "$WHOOP_ID" ]; then
  if [ -d "$BRIDGE" ]; then
    mkdir -p "$BRIDGE/mcp"
    cat > "$BRIDGE/mcp/.env" <<EOF
WHOOP_CLIENT_ID=${WHOOP_ID}
WHOOP_CLIENT_SECRET=${WHOOP_SECRET}
WHOOP_REDIRECT_URI=${WHOOP_REDIR}
EOF
    chmod 600 "$BRIDGE/mcp/.env"; pass "$BRIDGE/mcp/.env (chmod 600)"
  else
    warn "bridge repo not found at $BRIDGE — clone it (see RUNBOOK §3), then put WHOOP keys in $BRIDGE/mcp/.env"
  fi
fi

mkdir -p data
python3 - "$CHAT_MODEL" "$VISION_MODEL" "$USER_NAME" "$TZ_" <<'PY'
import json, os, sys
chat, vision, name, tz = sys.argv[1:5]
p = "data/settings.json"
s = json.load(open(p)) if os.path.exists(p) else {}
s.update({"default_model": chat, "vision_model": vision, "user_name": name, "timezone": tz})
json.dump(s, open(p, "w"), indent=2)
print("  PASS  data/settings.json")
PY

# ───────────────────────────── NEXT STEPS ─────────────────────────────
say "Next steps"
cat <<EOF
  1. Bring up the stack:     docker compose up -d --build
  2. Set up the bridge:      cd ${BRIDGE}
                             uv venv --python 3.12 mcp/.venv
                             uv pip install --python mcp/.venv -r mcp/requirements.txt
  3. Seed ledger + timers:   (charters/health.charter.yaml ships; genesis auto-seeds on first
                             run; install the com.myownhealth.* launchd plists — see RUNBOOK §7)
  4. Open:                   http://localhost:${APP_PORT}  (log in as ${ADMIN_USER})
$([ -z "$ADMIN_PASS" ] && echo '  NOTE: admin password was blank — the app generates a random one on first run and logs it.')
EOF
